
name: Deploy para GitHub Pages (branch gh-pages)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Injetar chave da API no config.js
        run: |
          echo "const apiKey = '${{ secrets.TOMORROW_API_KEY }}';" > docs/config.js

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
